# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/KarolChlasta/Perceptron/blob/master/Perceptron1.ipynb
"""

# A single McCulloch-Pitts neuron with 4 inputs
import numpy as np

mi = 4 # próg neuronu

inputs = np.array( [[0, 1, 0, 1],
                    [1, 1, 1, 0],
                    [0, 0, 1, 1],
                    [0, 1, 0, 0]])

w = np.array( [2, -1, 3, 5] )

print(inputs.dot(w1)-mi)

# Theta - activation function of my neuron
for x in (inputs.dot(w1)-mi):
  if x >= 0 :
    print(1)
  else :
    print(0)

# Neuron was activated three times.